This notebook is to clean my dataset!

In [3]:
!pip3 install -U ucimlrepo 

from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
apartment_for_rent_classified = fetch_ucirepo(id=555) 
  
# data (as pandas dataframes) 
X = apartment_for_rent_classified.data.features 
y = apartment_for_rent_classified.data.targets 
  
# metadata 
print(apartment_for_rent_classified.metadata) 
  
# variable information 
print(apartment_for_rent_classified.variables)

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.6-py3-none-any.whl.metadata (5.3 kB)
Downloading ucimlrepo-0.0.6-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.6
{'uci_id': 555, 'name': 'Apartment for Rent Classified', 'repository_url': 'https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified', 'data_url': 'https://archive.ics.uci.edu/static/public/555/data.csv', 'abstract': 'This is a dataset of classified for apartments for rent in USA.\n', 'area': 'Business', 'tasks': ['Classification', 'Regression', 'Clustering'], 'characteristics': ['Multivariate'], 'num_instances': 10000, 'num_features': 21, 'feature_types': ['Categorical', 'Integer'], 'demographics': [], 'target_col': None, 'index_col': ['id'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2019, 'last_updated': 'Mon Feb 26 2024', 'dataset_doi': '10.24432/C5X623', 'creators': [], 'intro_paper': None, 'additional_info': {'summary': "The dataset contains of 10'000 or 100'000 rows and of 22 columns The data has been cleaned in the way that \r\ncolumn price and square_feet never is empty but the dataset is saved as it was created.\r\n\r\nCan be used for different machine learning tasks such as clustering, classification and also regression for the squares feet column", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'id = unique identifier of apartment\ncategory = category of classified\ntitle = title text of apartment\nbody = body text of apartment\namenities = like AC, basketball,cable, gym, internet access, pool, refrigerator etc.\nbathrooms = number of bathrooms\nbedrooms = number of bedrooms\ncurrency = price in current\nfee = fee\nhas_photo = photo of apartment\npets_allowed = what pets are allowed dogs/cats etc.\nprice = rental price of apartment\nprice_display = price converted into display for reader\nprice_type = price in USD\nsquare_feet = size of the apartment\naddress =  where the apartment is located\ncityname =  where the apartment is located\nstate =  where the apartment is located\nlatitude = where the apartment is located\nlongitude = where the apartment is located\nsource = origin of classified\ntime = when classified was created', 'citation': None}}
             name     role         type demographic description units  \
0              id       ID      Integer        None        None  None
1        category  Feature  Categorical        None        None  None
2           title  Feature  Categorical        None        None  None
3            body  Feature  Categorical        None        None  None
4       amenities  Feature  Categorical        None        None  None
5       bathrooms  Feature      Integer        None        None  None
6        bedrooms  Feature  Categorical        None        None  None
7        currency  Feature  Categorical        None        None  None
8             fee  Feature  Categorical        None        None  None
9       has_photo  Feature  Categorical        None        None  None
10   pets_allowed  Feature  Categorical        None        None  None
11          price  Feature      Integer        None        None  None
12  price_display  Feature      Integer        None        None  None
13     price_type  Feature  Categorical        None        None  None
14    square_feet  Feature  Categorical        None        None  None
15        address  Feature  Categorical        None        None  None
16       cityname  Feature  Categorical        None        None  None
17          state  Feature      Integer        None        None  None
18       latitude  Feature      Integer        None        None  None
19      longitude  Feature  Categorical        None        None  None
20         source  Feature      Integer        None        None  None
21           time  Feature  Categorical        None        None  None

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11             no
12             no
13             no
14             no
15             no
16             no
17             no
18             no
19             no
20             no
21             no

/Users/yuritziavila-robledo/anaconda3/envs/finalNLP/lib/python3.10/site-packages/ucimlrepo/fetch.py:97: DtypeWarning: Columns (0,5,6,12,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)

In [4]:
import pandas as pd
# Example with low_memory=False
df = pd.read_csv('https://archive.ics.uci.edu/static/public/555/data.csv')
df.head()

/var/folders/4z/2hhh_brs3r7fjf6fj_zdz66w0000gn/T/ipykernel_4147/3300252001.py:3: DtypeWarning: Columns (0,5,6,12,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('https://archive.ics.uci.edu/static/public/555/data.csv')

,id,category,title,body,amenities,bathrooms,bedrooms,currency,fee,has_photo,...,price_display,price_type,square_feet,address,cityname,state,latitude,longitude,source,time
0,5668640009,housing/rent/apartment,One BR 507 & 509 Esplanade,"This unit is located at 507 & 509 Esplanade, R...",NaN,1,1,USD,No,Thumbnail,...,2195,Monthly,542,507 509 Esplanade,Redondo Beach,CA,33.8520,-118.3759,RentLingo,1.577360e+09
1,5668639818,housing/rent/apartment,Three BR 146 Lochview Drive,"This unit is located at 146 Lochview Drive, Ne...",NaN,1.5,3,USD,No,Thumbnail,...,1250,Monthly,1500,146 Lochview Dr,Newport News,VA,37.0867,-76.4941,RentLingo,1.577360e+09
2,5668639686,housing/rent/apartment,Three BR 3101 Morningside Drive,This unit is located at 3101 Morningside Drive...,NaN,2,3,USD,No,Thumbnail,...,1395,Monthly,1650,3101 Morningside Dr,Raleigh,NC,35.8230,-78.6438,RentLingo,1.577360e+09
3,5668639659,housing/rent/apartment,Two BR 209 Aegean Way,"This unit is located at 209 Aegean Way, Vacavi...",NaN,1,2,USD,No,Thumbnail,...,1600,Monthly,820,209 Aegean Way,Vacaville,CA,38.3622,-121.9712,RentLingo,1.577360e+09
4,5668639374,housing/rent/apartment,One BR 4805 Marquette NE,"This unit is located at 4805 Marquette NE, Alb...",NaN,1,1,USD,No,Thumbnail,...,975,Monthly,624,4805 Marquette NE,Albuquerque,NM,35.1038,-106.6110,RentLingo,1.577360e+09

In [ ]:
#cleaned_df_sample.to_csv("cleaned-sample.csv", index=False)

In [5]:
# Check for missing values
print(df.isnull().sum())

id                   0
category             0
title                0
body                 0
amenities        16077
bathrooms           66
bedrooms           127
currency             4
fee                  3
has_photo            3
pets_allowed     60634
price                5
price_display        6
price_type           3
square_feet          3
address          91880
cityname           305
state              305
latitude            29
longitude           31
source               6
time                 6
dtype: int64

In [7]:
# Renamed columns for latitude/longitude degrees
df.rename(columns={'latitude': 'latitude_deg', 'longitude': 'longitude_deg'}, inplace=True)

# Ensured consistent data types
df['price'] = df['price'].astype(float)
df['time'] = pd.to_datetime(df['time'], unit='s')

# Dropped rows with missing values
df.dropna(inplace=True)

            id                category  \
34  5668629745  housing/rent/apartment
37  5668627517  housing/rent/apartment
45  5668625536  housing/rent/apartment
46  5668625042  housing/rent/apartment
47  5668624921  housing/rent/apartment
48  5668624600  housing/rent/apartment
49  5668624330  housing/rent/apartment
51  5668624242  housing/rent/apartment
52  5668623348  housing/rent/apartment
54  5668622445  housing/rent/apartment
55  5668622093  housing/rent/apartment
56  5668621164  housing/rent/apartment
57  5668620432  housing/rent/apartment
58  5668619160  housing/rent/apartment
59  5668618357  housing/rent/apartment
61  5668615317  housing/rent/apartment
62  5668615207  housing/rent/apartment
63  5668615006  housing/rent/apartment
64  5668614703  housing/rent/apartment
65  5668614467  housing/rent/apartment

                                     title  \
34             One BR 24625 Wilderness Oak
37                    One BR 4092 Tpc Pkwy
45              One BR 4320 North Towne Ct
46                 Two BR 5235 Kester Ave.
47  Three BR 5206 Moonlight Drive Trail Sw
48          Studio apartment 815 18th St S
49                   Two BR 5402 Taney Ave
51                 Four BR 1535 W. Addison
52                One BR 2613 E Archer St.
54                One BR 5230 Eastwinds Dr
55             Studio apartment 1 Point St
56                   One BR 229 S Adams Rd
57                  One BR 745 Hamilton St
58                      Four BR 711 W. Elm
59             One BR 425 North 5th Street
61            Studio apartment 1500 7th St
62         One BR 701 Northeast Tudor Road
63     Three BR 6465 Longleaf Branch Drive
64                One BR 1010 Hwy 87 South
65                    Two BR 4456 Broadway

                                                 body  \
34  This unit is located at 24625 Wilderness Oak, ...
37  This unit is located at 4092 Tpc Pkwy, San Ant...
45  This unit is located at 4320 North Towne Ct, W...
46  This unit is located at 5235 Kester Ave., Sher...
47  This unit is located at 5206 Moonlight Drive T...
48  This unit is located at 815 18th St S, Arlingt...
49  This unit is located at 5402 Taney Ave, Alexan...
51  This unit is located at 1535 W. Addison, Chica...
52  This unit is located at 2613 E Archer St., Tul...
54  This unit is located at 5230 Eastwinds Dr, Orl...
55  This unit is located at one Point St, Providen...
56  This unit is located at 229 S Adams Rd, Spokan...
57  This unit is located at 745 Hamilton St, Somer...
58  This unit is located at 711 W. Elm, Urbana, 61...
59  This unit is located at 425 North fifth Street...
61  This unit is located at 1500 seventh St, Sacra...
62  This unit is located at 701 Northeast Tudor Ro...
63  This unit is located at 6465 Longleaf Branch D...
64  This unit is located at 1010 Hwy 87 South, Ora...
65  This unit is located at 4456 Broadway, Boulder...

                                            amenities bathrooms bedrooms  \
34               Dishwasher,Parking,Pool,Refrigerator         1        1
37      Dishwasher,Elevator,Parking,Pool,Refrigerator         1        1
45  Cable or Satellite,Dishwasher,Elevator,Firepla...         1        1
46                            Dishwasher,Parking,Pool         2        2
47  Dishwasher,Garbage Disposal,Patio/Deck,Refrige...         2        3
48                            Dishwasher,Refrigerator         1        2
49  Cable or Satellite,Dishwasher,Garbage Disposal...         1        2
51  Cable or Satellite,Dishwasher,Fireplace,Parkin...         2        4
52                               Parking,Refrigerator         1        1
54  Cable or Satellite,Clubhouse,Dishwasher,Doorma...         1        1
55  Cable or Satellite,Clubhouse,Dishwasher,Elevat...         1        2
56                                         Dishwasher         1        1
57  Cable or Satellite,Dishwasher,Elevator,Interne...         1        1
58  Dishwasher,Garbage Disposal,Patio/Deck,Refrige...         2        4
59                    Dishwasher,Parking,Refrigerator         1        1
61                                               Pool         1        2
62  Cable or Satellite,Clubhouse,Dishwasher,Garbag...         1        1
63      Dishwasher,Garbage Disposal,Pool,Refrigerator         2        3
64  Cable or Satellite,Clubhouse,Dishwasher,Garbag...         1        1
65  Dishwasher,Fireplace,Gated,Internet Access,Par...         1        2

   currency fee  has_photo  ... price_display  price_type square_feet  \
34      USD  No  Thumbnail  ...           975     Monthly         615
37      USD  No  Thumbnail  ...           975     Monthly         650
45      USD  No  Thumbnail  ...          1025     Monthly         616
46      USD  No  Thumbnail  ...          2548     Monthly        1391
47      USD  No  Thumbnail  ...          1299     Monthly        1119
48      USD  No  Thumbnail  ...          1549     Monthly         431
49      USD  No  Thumbnail  ...          1905     Monthly         900
51      USD  No  Thumbnail  ...          3580     Monthly        2100
52      USD  No  Thumbnail  ...           495     Monthly         360
54      USD  No  Thumbnail  ...           973     Monthly         509
55      USD  No  Thumbnail  ...          2095     Monthly         390
56      USD  No  Thumbnail  ...           750     Monthly         568
57      USD  No  Thumbnail  ...          1475     Monthly         663
58      USD  No  Thumbnail  ...          1650     Monthly        1100
59      USD  No  Thumbnail  ...          1200     Monthly         840
61      USD  No  Thumbnail  ...          1385     Monthly         572
62      USD  No  Thumbnail  ...          1007     Monthly         735
63      USD  No  Thumbnail  ...          1499     Monthly        1544
64      USD  No  Thumbnail  ...           671     Monthly         685
65      USD  No  Thumbnail  ...          1910     Monthly         745

                       address        cityname state latitude_deg  \
34        24625 Wilderness Oak     San Antonio    TX      29.4624
37            4092 Tpc Parkway     San Antonio    TX      29.4624
45      4320 North Towne Court         Windsor    WI      43.2128
46          5235 Kester Avenue    Sherman Oaks    CA      34.1542
47  5206 Moonlight Dr Trail SW         Concord    NC      35.4047
48               815 18th St S       Arlington    VA      38.8738
49           5402 Taney Avenue      Alexandria    VA      38.7999
51              1535 W Addison         Chicago    IL      41.8625
52            2613 E Archer St           Tulsa    OK      36.1160
54        5230 Eastwinds Drive         Orlando    FL      28.5163
55                  1 Point St      Providence    RI      41.8240
56            229 S Adams Road  Spokane Valley    WA      47.6485
57             745 Hamilton St        Somerset    NJ      40.4993
58                   711 W Elm          Urbana    IL      40.1171
59            425 North 5th St       Lafayette    IN      40.3613
61                 1500 7th St      Sacramento    CA      38.5587
62      701 Northeast Tudor Rd     Lees Summit    MO      38.9163
63     6465 Longleaf Branch Dr    Jacksonville    FL      30.2989
64       1010 Highway 87 South          Orange    TX      30.1213
65               4456 Broadway         Boulder    CO      40.0213

   longitude_deg     source                time
34      -98.5253  RentLingo 2019-12-26 11:27:23
37      -98.5253  RentLingo 2019-12-26 11:24:29
45      -89.3435  RentLingo 2019-12-26 11:22:01
46     -118.4447  RentLingo 2019-12-26 11:21:28
47      -80.6098  RentLingo 2019-12-26 11:21:19
48      -77.1055  RentLingo 2019-12-26 11:20:52
49      -77.1072  RentLingo 2019-12-26 11:20:32
51      -87.6825  RentLingo 2019-12-26 11:20:26
52      -95.9281  RentLingo 2019-12-26 11:19:32
54      -81.3644  RentLingo 2019-12-26 11:18:41
55      -71.4315  RentLingo 2019-12-26 11:18:23
56     -117.2657  RentLingo 2019-12-26 11:17:22
57      -74.5214  RentLingo 2019-12-26 11:16:38
58      -88.1889  RentLingo 2019-12-26 11:15:06
59      -86.9005  RentLingo 2019-12-26 11:14:10
61     -121.4320  RentLingo 2019-12-26 11:11:09
62      -94.3719  RentLingo 2019-12-26 11:10:59
63      -81.6324  RentLingo 2019-12-26 11:10:45
64      -93.7711  RentLingo 2019-12-26 11:10:23
65     -105.2552  RentLingo 2019-12-26 11:10:07

[20 rows x 22 columns]

In [9]:
#made a subset
subset_df_sample = df.sample(n=20, ignore_index=True)
subset_df_sample.head()

,id,category,title,body,amenities,bathrooms,bedrooms,currency,fee,has_photo,...,price_display,price_type,square_feet,address,cityname,state,latitude_deg,longitude_deg,source,time
0,5668610637,housing/rent/apartment,Three BR 16815 Shrub Oak Drive,"This unit is located at 16815 Shrub Oak Drive,...","Dishwasher,Refrigerator",2,3,USD,No,Thumbnail,...,1449,Monthly,1652,16815 Shrub Oak Dr,Humble,TX,30.0021,-95.2555,RentLingo,2019-12-26 11:05:43
1,5668618016,housing/rent/apartment,One BR 19216 Dr. John Lambert Drive,This unit is located at 19216 Dr. John Lambert...,"Cable or Satellite,Dishwasher,Gated,Internet A...",1,1,USD,No,Thumbnail,...,984,Monthly,752,19216 Drive John Lambert Dr,Hammond,LA,30.5007,-90.4760,RentLingo,2019-12-26 11:13:47
2,5668624113,housing/rent/apartment,Studio apartment 2238 Hyde Street,"This unit is located at 2238 Hyde Street, San ...",Refrigerator,1,2,USD,No,Thumbnail,...,4000,Monthly,417,2238 Hyde St,San Francisco,CA,37.7599,-122.4379,RentLingo,2019-12-26 11:20:16
3,5145459450,housing/rent/apartment,3431 Congo Dr,Colorado Springs Easy access to the plumbing a...,"AC,Basketball,Cable or Satellite,Clubhouse,Dis...",2,3,USD,No,Thumbnail,...,1200,Monthly,1160.0,3431 Congo Drive,Colorado Springs,CO,38.8021,-104.7105,RentDigs.com,2019-01-01 09:18:53
4,5648133316,housing/rent/apartment,One BR 5140 S Graystone Ave.,"This unit is located at 5140 S Graystone Ave.,...","Fireplace,Patio/Deck,Pool",1,1,USD,No,Thumbnail,...,929,Monthly,734,5140 S Graystone Avenue,Sioux Falls,SD,43.5329,-96.7265,RentLingo,2019-12-10 11:40:02

In [ ]:
subset_df_sample.to_csv("cleaned_sample.csv", index=False)